---
title: "BA810 Book Lab 5 - Resampling"
author: "Chiebuka Onwuzurike"
date: "2/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ISLR)
set.seed(1)
train=sample(392,196)
```

```{r}
lm.fit = lm(mpg~horsepower,data=Auto,subset = train)
```

```{r}
attach(Auto)
mean((mpg-predict(lm.fit,Auto))[-train]^2)
```
Can test for poly quadraic and cubic regression with poly()
```{r}
lm.fit2 = lm(mpg~poly(horsepower,2),data = Auto,subset = train)
mean((mpg-predict(lm.fit2,Auto))[-train]^2)

lm.fit3 = lm(mpg~poly(horsepower,3),data = Auto,subset = train)
mean((mpg-predict(lm.fit3,Auto))[-train]^2)
```
Lets try it again with a new seed to compare the variance
```{r}
set.seed(2)
train=sample(392,196)

lm.fit = lm(mpg~horsepower,data=Auto,subset = train)
mean((mpg-predict(lm.fit,Auto))[-train]^2)

lm.fit2 = lm(mpg~poly(horsepower,2),data = Auto,subset = train)
mean((mpg-predict(lm.fit2,Auto))[-train]^2)

lm.fit3 = lm(mpg~poly(horsepower,3),data = Auto,subset = train)
mean((mpg-predict(lm.fit3,Auto))[-train]^2)
```

```{r}

```

```{r}

```
